project_id = "wbgeqxscntiblzwxbzgn"

[functions.send-marketplace-notification]
verify_jwt = false

[functions.send-moderation-notification]
verify_jwt = false

[functions.send-trail-notification]
verify_jwt = false

[functions.send-trail-moderation]
verify_jwt = false

[functions.vipps-create-payment]
verify_jwt = false

[functions.vipps-webhook]
verify_jwt = false
