create table if not exists public.wildlife_camera_images (
  id bigint generated by default as identity primary key,
  camera_id text not null,
  gmail_message_id text not null,
  attachment_index integer not null check (attachment_index >= 0),
  image_path text not null,
  filename text not null,
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 15728640),
  sha256 text not null check (sha256 ~ '^[a-f0-9]{64}$'),
  received_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (gmail_message_id, attachment_index),
  unique (image_path)
);

create index if not exists wildlife_camera_images_camera_received_idx
  on public.wildlife_camera_images (camera_id, received_at desc);

alter table public.wildlife_camera_images enable row level security;

drop policy if exists "Alle kan lese viltkamerabilder" on public.wildlife_camera_images;
drop policy if exists "Offentlig lesing av fjellkamerabilder" on public.wildlife_camera_images;
create policy "Offentlig lesing av fjellkamerabilder"
  on public.wildlife_camera_images
  for select
  to anon, authenticated
  using (camera_id in ('modalen', 'byrkjefjell'));

revoke all on table public.wildlife_camera_images from anon, authenticated;
grant select (id, camera_id, image_path, received_at)
  on table public.wildlife_camera_images
  to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'wildlife-camera-images',
  'wildlife-camera-images',
  true,
  15728640,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
